version : '3'

services:
    web:
        build: .
        command: /env/bin/activate
        command: python manage.py makemigrations
        command: python manage.py migrate
        command: python manage.py runserver 0.0.0.0:8000
        ports:  
            - 8000:8000